---
spring:
  application.name: "PGMan"
  task.scheduling.pool.size: 4

pgman:
  dataSource:
    url: "jdbc:postgresql://172.17.42.1:5432/postgres"
    username: "postgres"
    password: "postgres"
  elasticsearch:
    host: "172.17.42.1"
    port: 9200
    username: "pgman"
    password: "32G?eCJHSPLudebT"
    protocol: "http"